### ISSUE TITLE
How is it going? 

### ISSUE THREAD

**Issue by cerkut** [NikolajAndersson/Freeverb#1]
I am keeping an eye on your implementation. In the filter branch, there is a bug as below. I think you are getting there, looking forward to test the improved class-based implementation.

`Matrix dimensions must agree.
Error in Freeverb/pComb (line 123)
            update(obj.pCombDelay, t + scaling*obj.pLowpass(o));

Error in Freeverb/rev (line 145)
            comb = pComb(p, x);

Error in Freeverb/process (line 191)
            out = rev(plugin, x);

Error in testbench_Freeverb (line 98)
        o1 = process(plugin, in(:,1:2));

Error in validateAudioPlugin `

**Comment by NikolajAndersson** [comment]
Great! Yes I noticed it when I implemented it (it is basically just copy - paste from the audioexample.FreeverbReverberator). When the frame size is changed after initialization, it returns an error in the dsp update(). The audioexample class has a fixed frame size to fix that, I have to do the same. 
But it is much more efficient now, the matlab profiler shows that the 16 comb filters are faster than the 8 allpass filters.

**Comment by NikolajAndersson** [comment]
Hi Cumhur,
I fixed the variable frame sizes. Now the problem is in the update function: 
"Reported by dsp.IIRFilter: This System object (or its current configuration) does not support
variable input sizes."

If I comment out line 119  update(obj.CombDelay, t + scaling*obj.Lowpass(o));, it will generate the VST.

**Comment by NikolajAndersson** [comment]
Hi Cumhur, the plugin in the filter branch should work now!

**Comment by cerkut** [comment]
Nice, yesterday I have noticed the push, today I will check how you did it :-)

Happy holidays, Cumhur

**Comment by NikolajAndersson** [comment]
Thank you! Happy holidays 👍
